[project]
name = "fin-news"
version = "0.1.0"
authors = [
    {name = "Gleb Pankov", email = "g@gpnkv.com"}
]
description = "fin-news is using 🗞 to explain 📈"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-aiplatform>=1.128.0",
    "google-cloud-bigquery>=3.30.0",
    "google-cloud-bigquery-storage>=2.35.0",
    "google-cloud-secret-manager>=2.25.0",
    "kfp>=2.13.0",
]
[dependency-groups]
dev = [
    "db-dtypes>=1.4.4",
    "ipywidgets>=8.1.5",
    "jupyter-resource-usage>=1.1.1",
    "jupyterlab>=4.3.5",
    "pytest>=8.3.4",
    "ruff>=0.14.5",
]

[tool.uv.workspace]
members = [
    "apps/informer_fusion",
    "apps/ravenpack_data",

    "packages/models",
    "packages/ravenpack_data",
]

# Mapping workspace members by *name* so others can depend on them
[tool.uv.sources]
fin-news-models = { workspace = true }
fin-news-ravenpack-data = { workspace = true }
